name: mkUtilsLegacy
description: mkUtilsLegacy is a lib for plugins development. By Mikael with help of Eduard and Koddy.
version: 4.1.7
softdepend: [ Vault ]
load: POSTWORLD
authors: [ Mikael, Eduard, Koddy ]
website: "https://github.com/MikaelMaster/mkUtilsLegacy"
main: com.mikael.mkutilslegacy.spigot.UtilsMain